// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkGpSLknuqG--Ts7YxKBi-25n00iRJIk',
    appId: '1:295645835466:web:891f049538df90d8aa0433',
    messagingSenderId: '295645835466',
    projectId: 'iris-rec',
    authDomain: 'iris-rec.firebaseapp.com',
    storageBucket: 'iris-rec.appspot.com',
    measurementId: 'G-V99MNR53LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoT10lLfTzqboZPBmMj05yj7g5IRMnmLk',
    appId: '1:295645835466:android:03cf9dde180ee887aa0433',
    messagingSenderId: '295645835466',
    projectId: 'iris-rec',
    storageBucket: 'iris-rec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvL4Q4WSglB9lx92aaTo2tAtIQlAM9Fhk',
    appId: '1:295645835466:ios:9f3fdae00ca028ffaa0433',
    messagingSenderId: '295645835466',
    projectId: 'iris-rec',
    storageBucket: 'iris-rec.appspot.com',
    iosBundleId: 'com.example.irisRec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvL4Q4WSglB9lx92aaTo2tAtIQlAM9Fhk',
    appId: '1:295645835466:ios:9f3fdae00ca028ffaa0433',
    messagingSenderId: '295645835466',
    projectId: 'iris-rec',
    storageBucket: 'iris-rec.appspot.com',
    iosBundleId: 'com.example.irisRec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZkGpSLknuqG--Ts7YxKBi-25n00iRJIk',
    appId: '1:295645835466:web:5a2b36c32b4ac37eaa0433',
    messagingSenderId: '295645835466',
    projectId: 'iris-rec',
    authDomain: 'iris-rec.firebaseapp.com',
    storageBucket: 'iris-rec.appspot.com',
    measurementId: 'G-V41VRFF8SX',
  );
}
